name: CI

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

permissions:
  pull-requests: write
  contents: read

jobs:
  commit-message-check:
    name: Commit Message Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    secrets: inherit

  trailing-newline-check:
    name: Trailing Newline Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_trailing-newline-check.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit

  typescript:
    name: TypeScript
    uses: valkyrjaio/.github/.github/workflows/_ts-typescript.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    with:
      ci-directory: .github/ci/typescript
      paths: |
        ci:
          - '.github/ci/typescript/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/typescript/**'
          - '.github/workflows/ci.yml'
          - 'src/**/*.ts'
          - 'bin/**/*.ts'
          - 'tests/**/*.ts'
          - 'tsconfig.json'
          - 'tsconfig.tests.json'
    secrets: inherit

  eslint:
    name: ESLint
    uses: valkyrjaio/.github/.github/workflows/_ts-eslint.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    with:
      ci-directory: .github/ci/eslint
      additional-directory: .github/ci/typescript
      paths: |
        ci:
          - '.github/ci/typescript/**'
          - '.github/ci/eslint/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/typescript/**'
          - '.github/ci/eslint/**'
          - '.github/workflows/ci.yml'
          - 'src/**/*.ts'
          - 'bin/**/*.ts'
          - 'tests/**/*.ts'
          - 'tsconfig.json'
          - 'tsconfig.tests.json'
    secrets: inherit

  prettier:
    name: Prettier
    uses: valkyrjaio/.github/.github/workflows/_ts-prettier.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    with:
      ci-directory: .github/ci/prettier
      paths: |
        ci:
          - '.github/ci/prettier/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/prettier/**'
          - '.github/workflows/ci.yml'
          - 'src/**/*.ts'
          - 'bin/**/*.ts'
          - 'tests/**/*.ts'
          - '*.json'
          - '*.md'
    secrets: inherit

  vitest:
    name: Vitest
    uses: valkyrjaio/.github/.github/workflows/_ts-vitest.yml@983fb2adea0987861f9ec402e6e7a13638119f2c
    with:
      ci-directory: .github/ci/vitest
      paths: |
        ci:
          - '.github/ci/vitest/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/vitest/**'
          - '.github/workflows/ci.yml'
          - 'src/**/*.ts'
          - 'tests/**/*.ts'
    secrets: inherit
