name: CI

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

permissions:
  pull-requests: write
  contents: read

jobs:
  commit-message-check:
    name: Commit Message Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    secrets: inherit

  trailing-newline-check:
    name: Trailing Newline Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_trailing-newline-check.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: .github/ci/typescript/package-lock.json

      - name: Install CI dependencies
        run: cd .github/ci/typescript && npm ci

      - name: Run TypeScript check
        run: npm run typescript

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: .github/ci/eslint/package-lock.json

      - name: Install CI dependencies
        run: cd .github/ci/typescript && npm ci && cd ../eslint && npm ci

      - name: Run ESLint
        run: npm run eslint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: .github/ci/prettier/package-lock.json

      - name: Install CI dependencies
        run: cd .github/ci/prettier && npm ci

      - name: Run Prettier check
        run: npm run prettier-check

  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: .github/ci/vitest/package-lock.json

      - name: Install CI dependencies
        run: cd .github/ci/vitest && npm ci

      - name: Run Vitest
        run: npm run vitest
