name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_ts-create-version-branch.yml@6bfd75231afaebd9e9681fe6b2ad2b9a083a6371
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "directory": ".github/ci/root-and-suggested"},
          {"name": "TypeScript",                  "directory": ".github/ci/typescript"},
          {"name": "ESLint",                      "directory": ".github/ci/eslint"},
          {"name": "Prettier",                    "directory": ".github/ci/prettier"},
          {"name": "Vitest",                      "directory": ".github/ci/vitest"}
        ]
