name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_ts-create-version-branch.yml@0f9937c07280c52b8480eb38de524a4ced39d363
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "directory": ".github/ci/root-and-suggested"},
          {"name": "TypeScript",                  "directory": ".github/ci/typescript"},
          {"name": "ESLint",                      "directory": ".github/ci/eslint"},
          {"name": "Prettier",                    "directory": ".github/ci/prettier"},
          {"name": "Vitest",                      "directory": ".github/ci/vitest"}
        ]
