name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-ts-version-branch.yml@396a3e938cf1c222f11e98afe54612d9170c0557
    secrets: inherit
    with:
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "directory": ".github/ci/root-and-suggested"},
          {"name": "TypeScript",                  "directory": ".github/ci/typescript"},
          {"name": "ESLint",                      "directory": ".github/ci/eslint"},
          {"name": "Prettier",                    "directory": ".github/ci/prettier"},
          {"name": "Vitest",                      "directory": ".github/ci/vitest"}
        ]
