name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump (auto, patch, feature, yearly, or rc)'
        required: true
        type: choice
        default: auto
        options:
          - auto
          - patch
          - feature
          - yearly
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: valkyrjaio/.github/.github/workflows/_ts-create-release.yml@699060a99b1eb0c346bc66dc33e99410f5de55d7
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      bump: ${{ inputs.bump }}
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "directory": ".github/ci/root-and-suggested"},
          {"name": "TypeScript",                  "directory": ".github/ci/typescript"},
          {"name": "ESLint",                      "directory": ".github/ci/eslint"},
          {"name": "Prettier",                    "directory": ".github/ci/prettier"},
          {"name": "Vitest",                      "directory": ".github/ci/vitest"}
        ]
      info-file-path: src/Valkyrja/Application/Constant/ApplicationInfo.ts
      info-file-name: ApplicationInfo

  publish:
    needs: release
    uses: valkyrjaio/.github/.github/workflows/_ts-release-npm-publish.yml@699060a99b1eb0c346bc66dc33e99410f5de55d7
