name: Update Dependencies

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: valkyrjaio/.github/.github/workflows/_ts-update-dependencies.yml@107d65ecb1d2cecc72c4839a53958f09ab753b9a
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "directory": "."},
          {"name": "Root and Suggested CI",       "directory": ".github/ci/root-and-suggested"},
          {"name": "TypeScript",                  "directory": ".github/ci/typescript"},
          {"name": "ESLint",                      "directory": ".github/ci/eslint"},
          {"name": "Prettier",                    "directory": ".github/ci/prettier"},
          {"name": "Vitest",                      "directory": ".github/ci/vitest"}
        ]
